Add tag component
AlchemyTelcoSolutions/apollo-price-releaser pull request #3
Opened 2021-03-03 16:01 UTC by iljahamalainenags

![Screenshot 2021-03-03 at 16 00 50](https://user-images.githubusercontent.com/79844421/109833984-a3526c00-7c39-11eb-8749-14e5c90ff57b.png)

2021-03-03 17:01 UTC, ianmilliken requested changes

2021-03-03 17:20 UTC, iljahamalainenags commented on src/components/tag/Tag.tsx
> +    </div>
thanks for the link! fixed.

2021-03-03 17:28 UTC, iljahamalainenags commented on src/components/tag/Tag.scss
> +}
done

2021-03-04 10:08 UTC, ianmilliken approved these changes

2021-03-04 10:20 UTC, merged