WIP: create selectbox component
AlchemyTelcoSolutions/apollo-price-releaser pull request #5
Opened 2021-03-05 11:03 UTC by iljahamalainenags

The new Selectbox component #AP-133

2021-03-05 11:17 UTC, ianmilliken commented on src/components/selectbox/Selectbox.tsx
> +export class Selectbox extends Component<SelectboxProps, SelectboxState> {
Please write functional components with hooks instead of class components

2021-03-05 11:19 UTC, ianmilliken commented on src/components/selectbox/Selectbox.tsx
> +            <ul className={"selectbox"}>
Please use CSS module syntax

2021-03-05 11:27 UTC, ianmilliken commented on src/index.scss
> +  user-select: none;
Looks like you are disabling user text selection for all HTML elements here, how come?

2021-03-05 12:40 UTC, iljahamalainenags commented on src/components/selectbox/Selectbox.tsx
> +export class Selectbox extends Component<SelectboxProps, SelectboxState> {
done

2021-03-08 14:23 UTC, ianmilliken commented on src/Router.tsx
> +                        {id: "1", name: "One", isSelected: true} as SelectboxItem,
Assuming the type assertion here is to stop the compiler complaining about the omitted `onChange` prop? If so it might be better to define that prop as optional when you declare the type so we don't lose autocompletion in the editor:
```
type SelectboxItem = { 
    // ... your others params,
    onChange?: ()=>void
}
```

2021-03-08 14:24 UTC, ianmilliken commented on src/components/selectbox/Selectbox.tsx
> +    onChange: ()=>void,
As mentioned in other comments, maybe worth setting `onChange` as an optional prop

2021-03-08 14:35 UTC, ianmilliken commented on src/components/selectbox/Selectbox.tsx
> +    const [items, setItems] = useState([] as SelectboxItem[]);
Better practice to use typescript generics over assertions, so something like this:
```
const [items, setItems] = useState<SelectboxItem[]>([])
```

2021-03-08 14:39 UTC, ianmilliken commented on src/components/selectbox/selectbox.module.scss
> +    top: $input-field-height + 5;
Is this functional with the omitted unit?

2021-03-08 14:40 UTC, ianmilliken requested changes
Just a few minor suggestions on your typescript

2021-03-08 17:08 UTC, iljahamalainenags commented on src/Router.tsx
> +                        {id: "1", name: "One", isSelected: true} as SelectboxItem,
fixed, thanks

2021-03-08 17:08 UTC, iljahamalainenags commented on src/components/selectbox/Selectbox.tsx
> +    onChange: ()=>void,
done

2021-03-08 17:09 UTC, iljahamalainenags commented on src/components/selectbox/Selectbox.tsx
> +    const [items, setItems] = useState([] as SelectboxItem[]);
oh, didn't know that. Thank you for pointing me to that!

2021-03-08 17:19 UTC, iljahamalainenags commented on src/components/selectbox/selectbox.module.scss
> +    top: $input-field-height + 5;
no, it is defined in the common.scss

2021-03-09 10:42 UTC, closed without merging