Price releaser view
AlchemyTelcoSolutions/apollo-price-releaser pull request #6
Opened 2021-03-10 11:14 UTC by iljahamalainenags

In this PR:
- added integration with Redux, created slice with reducers
- implemented layout of the page with selectboxes group
- tags and selectboxes are working together via shared state
- selectboxes may have either dynamic content loaded via HTTP request or hardcoded values

<img width="1495" alt="Screenshot 2021-03-10 at 11 07 05" src="https://user-images.githubusercontent.com/79844421/110620921-8665ed80-8191-11eb-9139-b71ca5c13ace.png">

2021-03-10 12:58 UTC, iljahamalainenags commented on src/views/price-releaser/priceReleaseSlice.ts
> +            } else {
yep, cheers

2021-03-11 10:52 UTC, ianmilliken requested changes
Minor changes

2021-03-11 10:52 UTC, ianmilliken commented on public/tick.icon.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
There are various tick components in react-feather, do we need this file too?

2021-03-11 10:52 UTC, ianmilliken commented on src/components/navbar/NavBar.tsx
> +            <li className={isActive(location.pathname, "/")}>
React Router has the [NavLink](https://reactrouter.com/web/api/NavLink) module to handle active styles, so you shouldn't need your own `isActive()` function

2021-03-11 10:52 UTC, ianmilliken commented on src/Router.tsx
> +                Market place release
Is this a placeholder?

2021-03-11 10:52 UTC, ianmilliken commented on src/components/navbar/navbar.module.scss
> +        font-size: 14px;
Just a note on fonts, colors, and other repeating values - we should start putting them into globally scoped vars for easy reuse.

2021-03-11 10:52 UTC, ianmilliken commented on src/components/selectbox/selectbox.module.scss
> +      .flagIcon IMG {
Sorry, nitpicking here but `img` not `IMG`

2021-03-11 10:52 UTC, ianmilliken commented on src/components/selectbox/selectbox.module.scss
> +        .flagIcon IMG {
Same as above

2021-03-11 10:52 UTC, ianmilliken commented on src/views/price-releaser/PriceReleaserView.tsx
> +const SelectBoxGroup = ({ title, description, url, initialItems, onChange, selected}: GroupProps) => {
Prefer to have one React component per file, please move SelectBoxGroup into its own file

2021-03-11 10:52 UTC, ianmilliken commented on src/components/selectbox/Selectbox.tsx
> +    return (<div className={styles.selectbox + " " + props.className}>
Prefer template literals strings to concatenated strings for readability, so something like 
```<div className={`${styles.selectbox} ${props.className}`}>```

2021-03-11 10:52 UTC, ianmilliken commented on src/components/selectbox/Selectbox.tsx
> +export const Selectbox: FunctionComponent<SelectboxProps> = (props) => {
Please destructure props

2021-03-11 10:56 UTC, iljahamalainenags commented on src/components/navbar/NavBar.tsx
> +            <li className={isActive(location.pathname, "/")}>
ahhh :))) cheers, didn't know that

2021-03-11 11:12 UTC, iljahamalainenags commented on public/tick.icon.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
replaced, thanks!

2021-03-11 11:42 UTC, iljahamalainenags commented on src/Router.tsx
> +                Market place release
yes, this page is not ready :)

2021-03-11 12:04 UTC, iljahamalainenags commented on src/components/selectbox/Selectbox.tsx
> +    return (<div className={styles.selectbox + " " + props.className}>
nice one! cheers!

2021-03-11 12:23 UTC, ianmilliken approved these changes

2021-03-11 12:52 UTC, carmo-evan approved these changes

2021-03-11 12:52 UTC, merged